# NollyHub Configuration

# Permissions
permissions:
  hub:
    default: 'nollyhub.default'
    admin: 'nollyhub.admin'

# Commands
commands:
  hub: 'hub'

# Hub Location
hub:
  world: null
  x: null
  y: null
  z: null
  yaw: null

# Features
features:
  disable_hunger: false
  disable_pvp: false
  protected_mode: false

# Messages
messages:
  welcome: <gold>Welcome to the <bold>Hub</bold>!</gold>
  hub_not_set: <red><bold>Hub has not been set yet.</bold></red>
  set_hub: <green>Hub location has been <bold>updated</bold>!</green>
  hub_too_low: <red><bold>Hub location is too low.</bold></red>
  reload: <green>You have <bold>successfully</bold> reloaded the configuration.</green>
  no_permission: <red><bold>You do not have permission to use this command.</bold></red>
  too_low: <red><bold>You are too low to use this command.</bold></red>
  reset_y: <red><bold>Y coordinate has been reset.</bold></red>
  invalid_action: "<red><bold><underline>Invalid action:</underline> {action}</bold></red>"
  protected_mode_interact: <red>You cannot interact while in protected mode.</red>
  bypass_enabled: <green>Bypass mode enabled.</green>
  bypass_disabled: <red>Bypass mode disabled.</red>
  features:
    invalid: "<red><bold>Invalid feature: {feature}</bold></red>"
    how_to_use: "<gold>Usage: /hub_feature [feature] [enable/disable/status]</gold>"
    already_enabled: <red><bold>Feature {feature} is already enabled.</bold></red>
    enabled: <green><bold>Feature {feature} has been enabled.</bold></green>
    already_disabled: <red><bold>Feature {feature} is already disabled.</bold></red>
    disabled: <green><bold>Feature {feature} has been disabled.</bold></green>
    enabled_status: <green><bold>Feature {feature} is currently enabled.</bold></green>
    disabled_status: <red><bold>Feature {feature} is currently disabled.</bold></red>