# Author informations
author: Nolly
website: https://thenolle.com
discord: https://discord.com/invite/86yVsMVN9z

# Plugin informations
name: NollyHub
version: 1.0.0
description: NollyHub is a comprehensive hub/spawn plugin designed for Minecraft servers. This plugin offers custom permissions, commands, messages, and aliases, all configurable through a user-friendly config.yml file. Designed and maintained by Nolly, NollyHub aims to offer a seamless, enjoyable experience for both server administrators and players.
main: com.thenolle.plugins.nollyhub.NollyHub


# Commands
commands:
  # Default command
  hub:
    description: Teleports the player to the hub.
    usage: /<command>
  # Admin command
  sethub:
    description: Sets the hub location.
    usage: /<command>
  # Admin command
  hub_reload:
    description: Reloads the plugin configuration.
    usage: /<command>

# Permissions
permissions:
  # Everyone has access to the hub command by default.
  nollyhub.default:
    description: Default permissions for NollyHub.
    default: true
  # Admins have access to all commands by default.
  nollyhub.admin:
    description: Admin permissions for NollyHub.
    default: op
